### ISSUE TITLE
Review needed

### ISSUE THREAD

**Issue by Elomidas** [PolytechLyon/isi3-tp2-visiteur-remond-jacoud-tp2#1]

**Comment by Slashgear** [comment]
- Pouvez vous m'expliquer le cas d'utilisation du pattern visiteur ?

- le rapport c'est bien 👍 

- On range les choses en packages (:warning:  les packages en java c'est en minuscule)

- Je comprends votre démarche de faire plusieurs visiteurs pour gérer les différents cas. Mais on casse un peu le principe ouvert fermé. La de la façon dont vous l'avez géré, si on rajoute des algo de parcours ou des types concrèt de noeuds, il faut ajouter du code à pas mal d'endroits.
Et ça c'est pas cool.

- votre `accepter` pourrait très bien retourner un type optionnel de Java (cf Optional<>)

**Comment by Slashgear** [comment]
hello @Elomidas petit UP sur votre TP !

**Comment by Elomidas** [comment]
Bonjour,
 *  On utilise le pattern visiteur lorsque l'on veut une ou plusieurs classes qui vont parcourir un arbre sans pour autant effectuer les mêmes actions sur les nœuds de celui-ci (comme ici l'affichage des nœuds qui n'a rien à voir avec le calcul de la hauteur).
 *  Classes rangées en packages.
 *  Suppression des diverses interfaces pour les différents visiteurs, et ajout d'un type de retour optionnel aux fonctions `accepter`.
